export const GET_COUPONS = 'GET_COUPONS';
export const LOAD_COUPONS_REQUEST = 'LOAD_COUPONS_REQUEST'
export const COUPONS_REQUEST_FAIL = 'COUPONS_REQUEST_FAIL'
export const GET_SINGLE_COUPON = 'GET_SINGLE_COUPON'
export const CREATE_COUPON = 'CREATE_COUPON'
export const UPDATE_COUPON = 'UPDATE_COUPON'